source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-contrib'
gem 'puma'
gem 'dotenv'
gem 'json'
gem 'sequel'
gem 'sqlite3'
gem 'telegram-bot-ruby'
gem 'faraday'
gem 'rack-cors'
gem 'rackup'

group :development do
  gem 'rubocop'
  gem 'pry'
  gem 'shotgun'
end
