source 'https://rubygems.org'

gem 'telegram-bot-ruby'
gem 'dotenv'
gem 'sequel'
gem 'sqlite3'
gem 'json'
gem 'faraday'
gem 'puma'
gem 'sinatra' # For webhook server

# Для парсинга меню
gem 'nokogiri'
gem 'httparty'
gem 'down'

group :development do
  gem 'rubocop'
  gem 'pry'
end 